### ISSUE TITLE
Changing license from MIT to Apache 2.0

### ISSUE THREAD

**Issue by iklevente** [iklevente/ChromiumForWindows#10]
Dear @stevennyman!

Since you are a contributor as well, I would like to ask if you're okay with changing this project's license to Apache License 2.0.

Here is a detailed description about the new license: https://choosealicense.com/licenses/apache-2.0/

It is similar to the old MIT License, but restricts trademark use and forks need to state the changes they make to the project.

**Comment by stevennyman** [comment]
Did anything happen that made this license change necessary or did it just seem like a better fit for the project? Stating changes might be helpful but not all forks will probably follow through with doing so.

**Comment by iklevente** [comment]
It just seems like a better fit for the project. Apache is just more explicit and there is some ambiguity around the MIT License.

There are only 2 forks to this project. Yours and one more who literally did nothing with it so it probably wouldn't cause any mess right now.

Others, who would fork this after license change, should follow the new license rules, if not, it wouldn't be a huge problem I guess. As I said it's just more precise to keep track of everything.

**Comment by stevennyman** [comment]
True, and GitHub already makes it fairly easy to determine the differences between a project and its forks.

I accept this license change.
