### ISSUE TITLE
[Feature request] Add support for Windows flags

### ISSUE THREAD

**Issue by eggplanting** [iklevente/ChromiumForWindows#3]
Hi,

it would be great if an option could be added, which adds Windows flags to the launched Chromium instance when started via your updater. This would allow to check Chromium for updates with each start while using user specific flags. Right now, I need to locate the chrome.exe, create a desktop icon and add the flags - Without having the update check.

Some examples for flags that can be used to run Chromium, when added to the desktop icon of Chromium:
 --no-default-browser-check --disable-logging --disable-breakpad --no-referrers

Probably done via a text file, where flags should just be entered and read by your updater when the file exists and flags were added.

List of supported Windows flags: https://peter.sh/experiments/chromium-command-line-switches/

**Comment by iklevente** [comment]
Added to plans ✅

**Comment by iklevente** [comment]
The new ChromiumForWindows 2.0 works differently, therefore it won't interfere in the Shortcut and Launch icons. You can add windows flags now just like you would with Google Chrome.
